server:
  port: 8000

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: first-service
          predicates:
            - Path=/first-service/**
          uri: http://localhost:8081/
          filters:
            - AddRequestHeader=first-request, dowon-lee
            - AddResponseHeader=first-response, Hi
        - id: second-service
          predicates:
            - Path=/second-service/**
          uri: http://localhost:8082/
          filters:
            - AddRequestHeader=second-header, kenneth
            - AddResponseHeader=second-response, Hello

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
